#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/..

if [ "$1" = "dev" ]; then
    npm run dev:frontend
else
    npm run start:frontend
fi